# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mapper_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mapper_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14mapper_service.proto\"i\n\x06MapReq\x12\x11\n\ttask_type\x18\x01 \x01(\x05\x12\x10\n\x08\x64\x61ta_dir\x18\x02 \x01(\t\x12\x12\n\nfile_names\x18\x03 \x03(\t\x12\x10\n\x08\x66ile_ids\x18\x04 \x03(\x05\x12\x14\n\x0creduce_count\x18\x05 \x01(\x05\"e\n\x07MapResp\x12\x10\n\x08temp_dir\x18\x01 \x01(\t\x12%\n\x06status\x18\x02 \x01(\x0e\x32\x15.MapResp.ResultStatus\"!\n\x0cResultStatus\x12\t\n\x05\x45RROR\x10\x00\x12\x06\n\x02OK\x10\x01\x32.\n\tMapWorker\x12!\n\nPerformMap\x12\x07.MapReq\x1a\x08.MapResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapper_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPREQ']._serialized_start=24
  _globals['_MAPREQ']._serialized_end=129
  _globals['_MAPRESP']._serialized_start=131
  _globals['_MAPRESP']._serialized_end=232
  _globals['_MAPRESP_RESULTSTATUS']._serialized_start=199
  _globals['_MAPRESP_RESULTSTATUS']._serialized_end=232
  _globals['_MAPWORKER']._serialized_start=234
  _globals['_MAPWORKER']._serialized_end=280
# @@protoc_insertion_point(module_scope)
