# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reducer_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'reducer_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15reducer_service.proto\"F\n\tReduceReq\x12\x11\n\ttask_type\x18\x01 \x01(\x05\x12\x12\n\npart_files\x18\x02 \x03(\t\x12\x12\n\noutput_dir\x18\x03 \x01(\t\"o\n\nReduceResp\x12(\n\x06status\x18\x01 \x01(\x0e\x32\x18.ReduceResp.ResultStatus\x12\x14\n\x0c\x66inal_output\x18\x02 \x01(\t\"!\n\x0cResultStatus\x12\t\n\x05\x45RROR\x10\x00\x12\x06\n\x02OK\x10\x01\x32:\n\x0cReduceWorker\x12*\n\rPerformReduce\x12\n.ReduceReq\x1a\x0b.ReduceResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reducer_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REDUCEREQ']._serialized_start=25
  _globals['_REDUCEREQ']._serialized_end=95
  _globals['_REDUCERESP']._serialized_start=97
  _globals['_REDUCERESP']._serialized_end=208
  _globals['_REDUCERESP_RESULTSTATUS']._serialized_start=175
  _globals['_REDUCERESP_RESULTSTATUS']._serialized_end=208
  _globals['_REDUCEWORKER']._serialized_start=210
  _globals['_REDUCEWORKER']._serialized_end=268
# @@protoc_insertion_point(module_scope)
