# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import byzantine_pb2 as byzantine__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in byzantine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ByzantineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunAlgorithm = channel.unary_unary(
                '/byzantine.ByzantineService/RunAlgorithm',
                request_serializer=byzantine__pb2.AlgorithmRequest.SerializeToString,
                response_deserializer=byzantine__pb2.AlgorithmResponse.FromString,
                _registered_method=True)
        self.SendOrder = channel.unary_unary(
                '/byzantine.ByzantineService/SendOrder',
                request_serializer=byzantine__pb2.OrderMessage.SerializeToString,
                response_deserializer=byzantine__pb2.Empty.FromString,
                _registered_method=True)
        self.GetDecision = channel.unary_unary(
                '/byzantine.ByzantineService/GetDecision',
                request_serializer=byzantine__pb2.Empty.SerializeToString,
                response_deserializer=byzantine__pb2.Decision.FromString,
                _registered_method=True)
        self.ResetLog = channel.unary_unary(
                '/byzantine.ByzantineService/ResetLog',
                request_serializer=byzantine__pb2.Empty.SerializeToString,
                response_deserializer=byzantine__pb2.Empty.FromString,
                _registered_method=True)


class ByzantineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunAlgorithm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ByzantineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunAlgorithm': grpc.unary_unary_rpc_method_handler(
                    servicer.RunAlgorithm,
                    request_deserializer=byzantine__pb2.AlgorithmRequest.FromString,
                    response_serializer=byzantine__pb2.AlgorithmResponse.SerializeToString,
            ),
            'SendOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOrder,
                    request_deserializer=byzantine__pb2.OrderMessage.FromString,
                    response_serializer=byzantine__pb2.Empty.SerializeToString,
            ),
            'GetDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDecision,
                    request_deserializer=byzantine__pb2.Empty.FromString,
                    response_serializer=byzantine__pb2.Decision.SerializeToString,
            ),
            'ResetLog': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetLog,
                    request_deserializer=byzantine__pb2.Empty.FromString,
                    response_serializer=byzantine__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'byzantine.ByzantineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('byzantine.ByzantineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ByzantineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunAlgorithm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/byzantine.ByzantineService/RunAlgorithm',
            byzantine__pb2.AlgorithmRequest.SerializeToString,
            byzantine__pb2.AlgorithmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/byzantine.ByzantineService/SendOrder',
            byzantine__pb2.OrderMessage.SerializeToString,
            byzantine__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/byzantine.ByzantineService/GetDecision',
            byzantine__pb2.Empty.SerializeToString,
            byzantine__pb2.Decision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/byzantine.ByzantineService/ResetLog',
            byzantine__pb2.Empty.SerializeToString,
            byzantine__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
