# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: byzantine.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'byzantine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62yzantine.proto\x12\tbyzantine\"-\n\x0bGeneralSpec\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nis_traitor\x18\x02 \x01(\x08\"V\n\x10\x41lgorithmRequest\x12\t\n\x01t\x18\x01 \x01(\x05\x12\r\n\x05order\x18\x02 \x01(\t\x12(\n\x08generals\x18\x03 \x03(\x0b\x32\x16.byzantine.GeneralSpec\"$\n\x04Vote\x12\r\n\x05order\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\">\n\x08\x44\x65\x63ision\x12\x12\n\ngeneral_id\x18\x01 \x01(\x05\x12\x1e\n\x05votes\x18\x02 \x03(\x0b\x32\x0f.byzantine.Vote\";\n\x11\x41lgorithmResponse\x12&\n\tdecisions\x18\x01 \x03(\x0b\x32\x13.byzantine.Decision\"_\n\x0cOrderMessage\x12\x14\n\x0c\x63ommander_id\x18\x01 \x01(\x05\x12\x11\n\tsender_id\x18\x02 \x01(\x05\x12\x17\n\x0frecursion_level\x18\x03 \x01(\x05\x12\r\n\x05order\x18\x04 \x01(\t\"\x07\n\x05\x45mpty2\xfb\x01\n\x10\x42yzantineService\x12I\n\x0cRunAlgorithm\x12\x1b.byzantine.AlgorithmRequest\x1a\x1c.byzantine.AlgorithmResponse\x12\x36\n\tSendOrder\x12\x17.byzantine.OrderMessage\x1a\x10.byzantine.Empty\x12\x34\n\x0bGetDecision\x12\x10.byzantine.Empty\x1a\x13.byzantine.Decision\x12.\n\x08ResetLog\x12\x10.byzantine.Empty\x1a\x10.byzantine.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'byzantine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERALSPEC']._serialized_start=30
  _globals['_GENERALSPEC']._serialized_end=75
  _globals['_ALGORITHMREQUEST']._serialized_start=77
  _globals['_ALGORITHMREQUEST']._serialized_end=163
  _globals['_VOTE']._serialized_start=165
  _globals['_VOTE']._serialized_end=201
  _globals['_DECISION']._serialized_start=203
  _globals['_DECISION']._serialized_end=265
  _globals['_ALGORITHMRESPONSE']._serialized_start=267
  _globals['_ALGORITHMRESPONSE']._serialized_end=326
  _globals['_ORDERMESSAGE']._serialized_start=328
  _globals['_ORDERMESSAGE']._serialized_end=423
  _globals['_EMPTY']._serialized_start=425
  _globals['_EMPTY']._serialized_end=432
  _globals['_BYZANTINESERVICE']._serialized_start=435
  _globals['_BYZANTINESERVICE']._serialized_end=686
# @@protoc_insertion_point(module_scope)
