# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: load_balancer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'load_balancer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13load_balancer.proto\x12\x0cloadbalancer\"F\n\x0b\x42\x61\x63kendInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x0c\n\x04load\x18\x04 \x01(\x02\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\nLoadReport\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04load\x18\x02 \x01(\x02\"8\n\rServerRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\"\x1e\n\x0bTaskRequest\x12\x0f\n\x07payload\x18\x01 \x01(\t\"\x1e\n\x0cTaskResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xea\x01\n\x0cLoadBalancer\x12L\n\x0fRegisterBackend\x12\x19.loadbalancer.BackendInfo\x1a\x1e.loadbalancer.RegisterResponse\x12\x46\n\nReportLoad\x12\x18.loadbalancer.LoadReport\x1a\x1e.loadbalancer.RegisterResponse\x12\x44\n\nGetBackend\x12\x1b.loadbalancer.ServerRequest\x1a\x19.loadbalancer.BackendInfo2O\n\x07\x43ompute\x12\x44\n\x0b\x43omputeTask\x12\x19.loadbalancer.TaskRequest\x1a\x1a.loadbalancer.TaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'load_balancer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BACKENDINFO']._serialized_start=37
  _globals['_BACKENDINFO']._serialized_end=107
  _globals['_REGISTERRESPONSE']._serialized_start=109
  _globals['_REGISTERRESPONSE']._serialized_end=161
  _globals['_LOADREPORT']._serialized_start=163
  _globals['_LOADREPORT']._serialized_end=201
  _globals['_SERVERREQUEST']._serialized_start=203
  _globals['_SERVERREQUEST']._serialized_end=259
  _globals['_TASKREQUEST']._serialized_start=261
  _globals['_TASKREQUEST']._serialized_end=291
  _globals['_TASKRESPONSE']._serialized_start=293
  _globals['_TASKRESPONSE']._serialized_end=323
  _globals['_LOADBALANCER']._serialized_start=326
  _globals['_LOADBALANCER']._serialized_end=560
  _globals['_COMPUTE']._serialized_start=562
  _globals['_COMPUTE']._serialized_end=641
# @@protoc_insertion_point(module_scope)
